name: Basic Structure
on: 
  # push:
  workflow_dispatch:
  

jobs:
  print-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hi!!!"
  print-2:
    runs-on: ubuntu-latest
    steps:
      - name: say Failed
        run: |
             echo "Failed!!!"
             exit 0
      - name: Say Success
        run: echo "Success!!!"